### ISSUE TITLE
Separate schemas into a separate repo

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/five-bells-shared#173]
`five-bells-shared` is being included in a number of places (such as https://github.com/interledgerjs/ilp-plugin-bells/pull/81) just for schemas and schema validation. It would be better if the schemas lived in their own repo that could be included where they are needed to avoid including a dependency that includes a lot of unused functionality.

**Comment by justmoon** [comment]
Perhaps schemas related to ILP should be extracted into a module `ilp-schemas` and schemas related to five-bells-ledger into a module `five-bells-schemas`.

**Comment by justmoon** [comment]
Done: https://github.com/interledgerjs/ilp-schemas
